### PR TITLE
Add emoji support, update views to reflect changes

### PR DESCRIPTION
**Pull request by skipperguy12**
Code needs to be reviewed

### CODE REVIEW

**Comment by ryanw-se** [comment]
Hell yeah! This is great, hopefully this gets merged soon.

**Comment by molenzwiebel** [comment]
What stops you from having a `topic.emojified_name`/`topic.rendered_name`/`topic.display_name` instead of `emojify(topic.name)` every time?

**Comment by skipperguy12** [comment]
@molenzwiebel thanks, changed it to that now

**Comment by skipperguy12** [comment]
Tested it for safety (sanitized), no issues with scripts or HTML.

**Comment by kblanks** [comment]
Looks good to me :+1:

**Comment by AustinLMayes** [comment]
:+1:

**Pull request merged**
